# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='dislike_author',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='question_key',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='usr_key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
