# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20171205_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
