# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20171208_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('question_key', 'like_author')]),
        ),
    ]
