# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20171211_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
