# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20171211_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likecount',
        ),
        migrations.AddField(
            model_name='like',
            name='rate',
            field=models.BooleanField(default=None),
        ),
    ]
