# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20171212_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='dislike_author',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='question_key',
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
