# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20171212_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
